nested_modal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects

  root :to => 'projects#index'

end

nested_modal/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true

end

nested_modal/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

nested_modal/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation
end

nested_modal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

nested_modal/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @projects = Project.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, tasks_attributes: [:id, :description, :done, :_destroy])
    end
end

nested_modal/app/helpers/application_helper.rb
module ApplicationHelper
end

nested_modal/app/helpers/projects_helper.rb
module ProjectsHelper
end

nested_modal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedModal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>


<div id="user_nav">
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>


</body>
</html>

nested_modal/app/views/projects/_form.html.erb
<%= form_for @project do |project_form| %>
    <div>
      <%= project_form.label :name, 'Project name:' %>
      <%= project_form.text_field :name %>
    </div>
    <% @project.tasks.each do |task| %>
        <% new_or_existing = task.new_record? ? 'new' : 'existing' %>
        <% prefix = "project[#{new_or_existing}_task_attributes][]" %>
        <% fields_for prefix, task do |task_form| %>
            <p>
            <div>
              <%= task_form.label :name, 'Task:' %>
              <%= task_form.text_field :name %>
            </div>

            <% unless task.new_record? %>
                <div>
                  <%= task_form.label :_delete, 'Remove:' %>
                  <%= task_form.check_box :_delete %>
                </div>
            <% end %>
            </p>
        <% end %>
    <% end %>

    <%= project_form.submit %>
<% end %>

nested_modal/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

nested_modal/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects List</h1>

<table>


  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

nested_modal/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<p id="notice"><%= notice %></p>

<h1>Projects List</h1>

<table>


  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', projects_path %>

nested_modal/app/views/projects/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>